version: "3.8"

networks:
  laravel_network:
    driver: bridge

services:
  backend:
    build:
      context: ./laravel-api-rest
      dockerfile: Dockerfile.dev
    container_name: backend
    ports:
      - 8000:8000
    volumes:
      - ./laravel-api-rest:/var/www
    depends_on:
      - db
    environment:
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - laravel_network
    entrypoint: ['/bin/sh', '-c']
    command:
      - |
        composer install
        php artisan migrate
        php artisan serve --host=0.0.0.0 --port=8000
  frontend:
    build:
      context: ./react-client
      dockerfile: Dockerfile.dev
    container_name: react_frontend
    restart: always
    volumes:
      - ./react-client:/app
      - /app/node_modules
    command: ["yarn", "dev", "--host"] 
    depends_on:
      - backend
    networks:
      - laravel_network

  nginx:
    image: nginx:latest
    container_name: nginx_server
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    networks:
      - laravel_network


  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel_network

volumes:
  pgdata:
