version: "3.8"

networks:
  laravel_network:
    driver: bridge

services:
  backend:
    build:
      context: ./laravel-rest-api
      dockerfile: Dockerfile.dev
    container_name: laravel_backend
    restart: always
    working_dir: /var/www
    volumes:
      - ./laravel-rest-api:/var/www
    env_file:
      - ./laravel-rest-api/.env
    depends_on:
      - db
    networks:
      - laravel_network
    ports:
      - "9000:9000"
    environment:
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}

  frontend:
    build:
      context: ./laravel-api-client
      dockerfile: Dockerfile.dev
    container_name: react_frontend
    restart: always
    volumes:
      - ./laravel-api-client:/app
      - /app/node_modules
    command: ["yarn", "dev", "--host"] 
    depends_on:
      - backend
    networks:
      - laravel_network

  nginx:
    image: nginx:latest
    container_name: nginx_server
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    networks:
      - laravel_network


  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel_network

volumes:
  pgdata:
